"""Data models and schemas for Milestone 4 Multi-Agent Conversational Platform.

Covers:
- Query Understanding models with Domain Awareness
- ClarificationType, ClarificationRequest & ClarificationStatus
- ConversationTurn & ConversationSession with Domain Segregation
- SpeechConfig & VoicePayload
- TransparencyScoreBreakdown & TransparencyPanelPayload
- RetrievalResult, SourceAttribution, AgentResponse & OrchestrationResult
"""
import time
import uuid
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import List, Dict, Any, Optional

class QueryType(str, Enum):
    FACTUAL = "factual"
    PROCEDURAL = "procedural"
    COMPARATIVE = "comparative"
    AMBIGUOUS = "ambiguous"
    MULTI_PART = "multi_part"

class RoutingTarget(str, Enum):
    RETRIEVAL = "retrieval"
    CLARIFICATION = "clarification"

class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NONE = "NONE"

class ClarificationType(str, Enum):
    AMBIGUOUS_TERM = "ambiguous_term"
    MISSING_CONTEXT = "missing_context"
    INCOMPLETE_REQUEST = "incomplete_request"
    MULTIPLE_INTERPRETATIONS = "multiple_interpretations"
    MULTI_PART_UNRESOLVED = "multi_part_unresolved"
    INSUFFICIENT_INFORMATION = "insufficient_information"

class ClarificationStatus(str, Enum):
    PENDING = "pending"
    RESOLVED = "resolved"
    CANCELLED = "cancelled"

@dataclass
class ClarificationRequest:
    """Detailed clarification proposal produced by the Clarification Agent."""
    original_query: str
    clarification_type: ClarificationType
    reason: str
    follow_up_question: str
    suggested_options: List[str] = field(default_factory=list)
    sub_questions: List[str] = field(default_factory=list)
    is_multi_part: bool = False
    clarification_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    status: ClarificationStatus = ClarificationStatus.PENDING
    created_at: float = field(default_factory=time.time)
    resolved_at: Optional[float] = None
    user_response: Optional[str] = None
    refined_query: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "clarification_id": self.clarification_id,
            "original_query": self.original_query,
            "clarification_type": self.clarification_type.value,
            "reason": self.reason,
            "follow_up_question": self.follow_up_question,
            "suggested_options": self.suggested_options,
            "sub_questions": self.sub_questions,
            "is_multi_part": self.is_multi_part,
            "status": self.status.value,
            "created_at": self.created_at,
            "resolved_at": self.resolved_at,
            "user_response": self.user_response,
            "refined_query": self.refined_query
        }

@dataclass
class QueryAnalysisResult:
    """Output generated by Query Understanding Agent."""
    query: str
    cleaned_query: str
    query_type: QueryType
    domain: str = "general"
    classification_confidence: float = 0.0
    route_to: RoutingTarget = RoutingTarget.RETRIEVAL
    reasoning: str = ""
    entities: List[str] = field(default_factory=list)
    requires_clarification: bool = False
    clarification_request: Optional[ClarificationRequest] = None
    reformulated_query: Optional[str] = None
    sub_questions: List[str] = field(default_factory=list)
    confidence: Optional[float] = None

    def __post_init__(self):
        if self.confidence is not None and not self.classification_confidence:
            self.classification_confidence = self.confidence
        elif self.classification_confidence and self.confidence is None:
            self.confidence = self.classification_confidence

@dataclass
class RetrievalChunk:
    """A retrieved text chunk accompanied by relevance score and metadata."""
    chunk_id: str
    document_name: str
    content: str
    score: float
    rank: int
    page: Optional[int] = None
    section: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class RetrievalResult:
    """Container for chunks returned by the Retrieval Agent."""
    query: str
    chunks: List[RetrievalChunk] = field(default_factory=list)
    top_score: float = 0.0
    average_score: float = 0.0
    total_candidates: int = 0
    filter_threshold: float = 0.0
    execution_time_ms: float = 0.0

@dataclass
class SourceAttribution:
    """Document attribution indicating where specific factual claims originated."""
    document_name: str
    chunk_id: str
    relevance_score: float
    page: Optional[int] = None
    section: Optional[str] = None
    snippet: str = ""

@dataclass
class SpeechConfig:
    """Configuration payload for Text-to-Speech playback in browser."""
    rate: float = 1.0
    pitch: float = 1.0
    volume: float = 1.0
    lang: str = "en-US"

@dataclass
class VoicePayload:
    """Voice interaction payload combining raw and clean spoken text."""
    spoken_text: str
    speech_config: SpeechConfig = field(default_factory=SpeechConfig)
    is_voice_enabled: bool = True

@dataclass
class TransparencyScoreBreakdown:
    """Granular empirical formula breakdown: Confidence = 0.70 * TopScore + 0.30 * AvgTopK."""
    top_chunk_score: float
    avg_top_k_score: float
    weight_top: float = 0.70
    weight_avg: float = 0.30
    combined_score: float = 0.0
    confidence_level: ConfidenceLevel = ConfidenceLevel.NONE

    def __post_init__(self):
        if self.combined_score == 0.0 and (self.top_chunk_score > 0 or self.avg_top_k_score > 0):
            self.combined_score = round(
                self.weight_top * self.top_chunk_score + self.weight_avg * self.avg_top_k_score,
                4
            )
            if self.combined_score >= 0.70:
                self.confidence_level = ConfidenceLevel.HIGH
            elif self.combined_score >= 0.45:
                self.confidence_level = ConfidenceLevel.MEDIUM
            elif self.combined_score > 0.0:
                self.confidence_level = ConfidenceLevel.LOW
            else:
                self.confidence_level = ConfidenceLevel.NONE

@dataclass
class TransparencyPanelPayload:
    """Comprehensive transparency metadata for auditing."""
    score_breakdown: TransparencyScoreBreakdown
    ranked_chunks: List[RetrievalChunk]
    source_attributions: List[SourceAttribution]
    query_type: QueryType
    routing_target: RoutingTarget
    anaphora_rewritten_query: Optional[str] = None
    clarification_occurred: bool = False
    clarification_type: Optional[ClarificationType] = None
    is_multi_turn: bool = False
    turn_index: int = 1

@dataclass
class ConversationTurn:
    """A single turn in a multi-turn conversation session."""
    query: str
    effective_query: str
    response: str
    confidence_score: float
    sources: List[str]
    key_entities: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)
    transparency: Optional[TransparencyPanelPayload] = None
    domain: str = "general"

@dataclass
class ConversationSession:
    """Multi-turn session maintaining rolling conversation history and entity bindings."""
    session_id: str
    turns: List[ConversationTurn] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    last_active: float = field(default_factory=time.time)
    active_domain: str = "general"

    def add_turn(self, turn: ConversationTurn, max_history: int = 10):
        self.turns.append(turn)
        self.last_active = time.time()
        self.active_domain = turn.domain
        if len(self.turns) > max_history:
            self.turns = self.turns[-max_history:]

    def get_last_turn(self) -> Optional[ConversationTurn]:
        return self.turns[-1] if self.turns else None

@dataclass
class AgentResponse:
    """Final grounded synthesis generated by Response Generation Agent."""
    answer: str
    confidence_score: float
    confidence_level: ConfidenceLevel
    sources: List[str]
    query_analysis: QueryAnalysisResult
    has_sufficient_evidence: bool = True
    requires_clarification: bool = False
    clarification_request: Optional[ClarificationRequest] = None
    transparency: Optional[TransparencyPanelPayload] = None
    voice: Optional[VoicePayload] = None
    spoken_text: Optional[str] = None
    is_clarified_resolution: bool = False
    refined_query: Optional[str] = None

@dataclass
class OrchestrationResult:
    """Unified result encapsulating the complete pipeline execution."""
    query: str
    response: AgentResponse
    retrieval_result: Optional[RetrievalResult] = None
    execution_time_ms: float = 0.0
    status: str = "success"
    error: Optional[str] = None
    clarification_request: Optional[ClarificationRequest] = None
    session_id: Optional[str] = None
    input_modality: str = "text"
