"""Data models and schemas for Milestone 3 Multi-Agent Conversational Platform.

Covers:
- Query Understanding models (M2/M3)
- ClarificationType, ClarificationRequest & ClarificationStatus (M3.1)
- ConversationTurn & ConversationSession (M3.2)
- SpeechConfig & VoicePayload (M3.3)
- TransparencyScoreBreakdown & TransparencyPanelPayload (M3.4)
- RetrievalResult, SourceAttribution, AgentResponse & OrchestrationResult
"""
import time
import uuid
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import List, Dict, Any, Optional

class QueryType(str, Enum):
    FACTUAL = "factual"
    PROCEDURAL = "procedural"
    COMPARATIVE = "comparative"
    AMBIGUOUS = "ambiguous"
    MULTI_PART = "multi_part"

class RoutingTarget(str, Enum):
    RETRIEVAL = "retrieval"
    CLARIFICATION = "clarification"

class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NONE = "NONE"

class ClarificationType(str, Enum):
    AMBIGUOUS_TERM = "ambiguous_term"
    MISSING_CONTEXT = "missing_context"
    INCOMPLETE_REQUEST = "incomplete_request"
    MULTIPLE_INTERPRETATIONS = "multiple_interpretations"
    MULTI_PART_UNRESOLVED = "multi_part_unresolved"
    INSUFFICIENT_INFORMATION = "insufficient_information"

class ClarificationStatus(str, Enum):
    PENDING = "pending"
    RESOLVED = "resolved"
    CANCELLED = "cancelled"

@dataclass
class ClarificationRequest:
    """Detailed clarification proposal produced by the Clarification Agent (M3.1)."""
    original_query: str
    clarification_type: ClarificationType
    reason: str
    follow_up_question: str
    suggested_options: List[str] = field(default_factory=list)
    sub_questions: List[str] = field(default_factory=list)
    is_multi_part: bool = False
    clarification_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    status: ClarificationStatus = ClarificationStatus.PENDING
    created_at: float = field(default_factory=time.time)
    resolved_at: Optional[float] = None
    user_response: Optional[str] = None
    refined_query: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "clarification_id": self.clarification_id,
            "original_query": self.original_query,
            "clarification_type": self.clarification_type.value,
            "reason": self.reason,
            "follow_up_question": self.follow_up_question,
            "suggested_options": self.suggested_options,
            "sub_questions": self.sub_questions,
            "is_multi_part": self.is_multi_part,
            "status": self.status.value,
            "created_at": self.created_at,
            "resolved_at": self.resolved_at,
            "user_response": self.user_response,
            "refined_query": self.refined_query
        }

@dataclass
class QueryAnalysisResult:
    """Output generated by Query Understanding Agent."""
    query: str
    cleaned_query: str
    query_type: QueryType
    classification_confidence: float = 0.0
    route_to: RoutingTarget = RoutingTarget.RETRIEVAL
    reasoning: str = ""
    entities: List[str] = field(default_factory=list)
    requires_clarification: bool = False
    clarification_request: Optional[ClarificationRequest] = None
    reformulated_query: Optional[str] = None
    sub_questions: List[str] = field(default_factory=list)
    confidence: Optional[float] = None

    def __post_init__(self):
        if self.confidence is not None and not self.classification_confidence:
            self.classification_confidence = self.confidence
        elif self.classification_confidence and self.confidence is None:
            self.confidence = self.classification_confidence

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "cleaned_query": self.cleaned_query,
            "query_type": self.query_type.value,
            "classification_confidence": self.classification_confidence,
            "confidence": self.classification_confidence,
            "route_to": self.route_to.value,
            "reasoning": self.reasoning,
            "entities": self.entities,
            "requires_clarification": self.requires_clarification,
            "clarification_request": self.clarification_request.to_dict() if self.clarification_request else None,
            "reformulated_query": self.reformulated_query,
            "sub_questions": self.sub_questions
        }

@dataclass
class RetrievalChunk:
    """A ranked knowledge base chunk with metadata and similarity score."""
    chunk_id: str
    content: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    similarity_score: float = 0.0
    rank: int = 1
    document_name: str = ""
    page: Optional[int] = None
    section: Optional[str] = None
    score: Optional[float] = None

    def __post_init__(self):
        if self.score is not None and not self.similarity_score:
            self.similarity_score = self.score
        elif self.similarity_score and self.score is None:
            self.score = self.similarity_score

        if not self.document_name and self.metadata:
            self.document_name = self.metadata.get("document_name") or self.metadata.get("source", "Unknown")
        if self.page is None and self.metadata:
            raw_page = self.metadata.get("page")
            self.page = raw_page if (raw_page is not None and raw_page != 0) else None
        if self.section is None and self.metadata:
            self.section = self.metadata.get("section")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "chunk_id": self.chunk_id,
            "content": self.content,
            "metadata": self.metadata,
            "similarity_score": self.similarity_score,
            "score": self.similarity_score,
            "rank": self.rank,
            "document_name": self.document_name,
            "page": self.page,
            "section": self.section
        }

@dataclass
class RetrievalResult:
    """Output generated by the Retrieval Agent."""
    query: str
    query_type: QueryType
    chunks: List[RetrievalChunk]
    top_score: float
    total_retrieved: int
    filtered_count: int
    has_sufficient_evidence: bool
    confidence_threshold: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "query_type": self.query_type.value,
            "chunks": [c.to_dict() for c in self.chunks],
            "top_score": self.top_score,
            "total_retrieved": self.total_retrieved,
            "filtered_count": self.filtered_count,
            "has_sufficient_evidence": self.has_sufficient_evidence,
            "confidence_threshold": self.confidence_threshold
        }

@dataclass
class SourceAttribution:
    """Citation metadata for grounded response attribution."""
    document_name: str
    chunk_id: str
    relevance_score: float
    snippet: str
    page: Optional[int] = None
    section: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "document_name": self.document_name,
            "chunk_id": self.chunk_id,
            "relevance_score": self.relevance_score,
            "snippet": self.snippet,
            "page": self.page,
            "section": self.section
        }

@dataclass
class TransparencyScoreBreakdown:
    """Detailed formula breakdown for response confidence calculation (M3.4)."""
    top_chunk_score: float
    avg_top_k_score: float
    combined_score: float
    threshold: float
    confidence_level: ConfidenceLevel
    formula: str = "70% * Top-Chunk-Score + 30% * Avg-Top-K-Score"
    top_k_count: int = 0
    low_confidence_reasons: List[str] = field(default_factory=list)

    @property
    def combined_confidence(self) -> float:
        return self.combined_score

    @classmethod
    def from_chunks(
        cls,
        chunks: List[RetrievalChunk],
        threshold: float = 0.45
    ) -> "TransparencyScoreBreakdown":
        if not chunks:
            return cls(
                top_chunk_score=0.0,
                avg_top_k_score=0.0,
                combined_score=0.0,
                threshold=threshold,
                confidence_level=ConfidenceLevel.NONE,
                top_k_count=0,
                low_confidence_reasons=["No chunks retrieved from knowledge base."]
            )

        top_chunk_score = chunks[0].similarity_score if chunks[0].similarity_score is not None else 0.0
        scores = [c.similarity_score for c in chunks if c.similarity_score is not None]
        avg_score = sum(scores) / len(scores) if scores else 0.0
        combined = round(0.7 * top_chunk_score + 0.3 * avg_score, 4)

        if combined >= 0.70:
            level = ConfidenceLevel.HIGH
        elif combined >= 0.50:
            level = ConfidenceLevel.MEDIUM
        elif combined >= threshold:
            level = ConfidenceLevel.LOW
        else:
            level = ConfidenceLevel.NONE

        low_reasons = []
        if top_chunk_score < 0.50:
            low_reasons.append(f"Top chunk relevance is below 0.50 ({top_chunk_score:.2f}).")
        if combined < threshold:
            low_reasons.append(f"Combined score ({combined:.2f}) falls below threshold ({threshold:.2f}).")

        return cls(
            top_chunk_score=round(top_chunk_score, 4),
            avg_top_k_score=round(avg_score, 4),
            combined_score=combined,
            threshold=threshold,
            confidence_level=level,
            top_k_count=len(chunks),
            low_confidence_reasons=low_reasons
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "top_chunk_score": self.top_chunk_score,
            "avg_top_k_score": self.avg_top_k_score,
            "combined_score": self.combined_score,
            "threshold": self.threshold,
            "confidence_level": self.confidence_level.value,
            "formula": self.formula,
            "top_k_count": self.top_k_count,
            "low_confidence_reasons": self.low_confidence_reasons
        }

@dataclass
class TransparencyPanelPayload:
    """Structured transparency payload for deep evidence inspection (M3.4)."""
    retrieved_chunks: List[RetrievalChunk]
    citations: List[SourceAttribution]
    score_breakdown: TransparencyScoreBreakdown
    query: str = ""
    refined_query: Optional[str] = None
    confidence_level: ConfidenceLevel = ConfidenceLevel.MEDIUM
    confidence_score: float = 0.0
    source_documents: List[str] = field(default_factory=list)
    evidence_sufficient: bool = True
    low_confidence_reason: Optional[str] = None
    filtered_out_count: int = 0

    def __post_init__(self):
        if not self.confidence_score:
            self.confidence_score = self.score_breakdown.combined_score
        if not self.confidence_level:
            self.confidence_level = self.score_breakdown.confidence_level
        if not self.source_documents and self.citations:
            self.source_documents = list(dict.fromkeys(c.document_name for c in self.citations))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "refined_query": self.refined_query,
            "confidence_level": self.confidence_level.value,
            "confidence_score": self.confidence_score,
            "score_breakdown": self.score_breakdown.to_dict(),
            "source_documents": self.source_documents,
            "retrieved_chunks": [c.to_dict() for c in self.retrieved_chunks],
            "citations": [c.to_dict() for c in self.citations],
            "evidence_sufficient": self.evidence_sufficient,
            "low_confidence_reason": self.low_confidence_reason,
            "filtered_out_count": self.filtered_out_count
        }

@dataclass
class SpeechConfig:
    """Configuration settings for Web Speech API TTS (M3.3)."""
    text: str = ""
    language: str = "en-US"
    rate: float = 1.0
    pitch: float = 1.0
    voice_name: Optional[str] = None
    auto_speak: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "text": self.text,
            "language": self.language,
            "rate": self.rate,
            "pitch": self.pitch,
            "voice_name": self.voice_name,
            "auto_speak": self.auto_speak
        }

@dataclass
class AgentResponse:
    """Output generated by the Response Generation or Clarification Agent."""
    answer: str
    confidence_score: float
    confidence_level: ConfidenceLevel
    sources: List[SourceAttribution]
    query_analysis: QueryAnalysisResult
    has_sufficient_evidence: bool = True
    requires_clarification: bool = False
    clarification_request: Optional[ClarificationRequest] = None
    is_clarified_resolution: bool = False
    refined_query: Optional[str] = None
    transparency_payload: Optional[TransparencyPanelPayload] = None
    spoken_text: Optional[str] = None

    @property
    def transparency(self) -> Optional[TransparencyPanelPayload]:
        return self.transparency_payload

    def to_dict(self) -> Dict[str, Any]:
        return {
            "answer": self.answer,
            "confidence_score": self.confidence_score,
            "confidence_level": self.confidence_level.value,
            "sources": [s.to_dict() for s in self.sources],
            "query_analysis": self.query_analysis.to_dict(),
            "has_sufficient_evidence": self.has_sufficient_evidence,
            "requires_clarification": self.requires_clarification,
            "clarification_request": self.clarification_request.to_dict() if self.clarification_request else None,
            "is_clarified_resolution": self.is_clarified_resolution,
            "refined_query": self.refined_query,
            "transparency_payload": self.transparency_payload.to_dict() if self.transparency_payload else None,
            "spoken_text": self.spoken_text
        }

@dataclass
class ConversationTurn:
    """Represents a single multi-turn interaction in Conversation Memory (M3.2)."""
    user_query: str = ""
    contextualized_query: str = ""
    response: Any = None
    entities: List[str] = field(default_factory=list)
    referenced_docs: List[str] = field(default_factory=list)
    intent_type: QueryType = QueryType.FACTUAL
    turn_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    timestamp: float = field(default_factory=time.time)
    # Compatibility aliases
    query: Optional[str] = None
    effective_query: Optional[str] = None
    confidence_score: Optional[float] = None
    sources: Optional[List[Any]] = None
    key_entities: Optional[List[str]] = None
    transparency: Optional[Any] = None

    def __post_init__(self):
        if self.query and not self.user_query:
            self.user_query = self.query
        elif self.user_query and not self.query:
            self.query = self.user_query

        if self.effective_query and not self.contextualized_query:
            self.contextualized_query = self.effective_query
        elif self.contextualized_query and not self.effective_query:
            self.effective_query = self.contextualized_query

        if self.key_entities and not self.entities:
            self.entities = self.key_entities
        elif self.entities and not self.key_entities:
            self.key_entities = self.entities

    def to_dict(self) -> Dict[str, Any]:
        resp_dict = self.response.to_dict() if (self.response and hasattr(self.response, "to_dict")) else self.response
        return {
            "turn_id": self.turn_id,
            "user_query": self.user_query,
            "query": self.user_query,
            "contextualized_query": self.contextualized_query,
            "effective_query": self.contextualized_query,
            "response": resp_dict,
            "entities": self.entities,
            "referenced_docs": self.referenced_docs,
            "intent_type": self.intent_type.value if hasattr(self.intent_type, "value") else str(self.intent_type),
            "timestamp": self.timestamp
        }


@dataclass
class ConversationSession:
    """Manages active conversation session memory and turn history (M3.2)."""
    session_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    turns: List[ConversationTurn] = field(default_factory=list)
    active_clarification: Optional[ClarificationRequest] = None
    max_turns: int = 10
    created_at: float = field(default_factory=time.time)
    entity_history: List[str] = field(default_factory=list)
    primary_topic: Optional[str] = None

    def add_turn(self, turn: ConversationTurn) -> None:
        """Append turn, update entity history, and apply sliding window pruning."""
        self.turns.append(turn)
        for e in turn.entities:
            if e not in self.entity_history:
                self.entity_history.append(e)
        if turn.entities:
            self.primary_topic = turn.entities[0]
        # Prune oldest turns if exceeding max_turns
        if len(self.turns) > self.max_turns:
            self.turns = self.turns[-self.max_turns:]

    def get_last_turn(self) -> Optional[ConversationTurn]:
        """Return most recent conversation turn."""
        return self.turns[-1] if self.turns else None

    def get_recent_turns(self, k: int = 3) -> List[ConversationTurn]:
        """Return the most recent k turns."""
        return self.turns[-k:] if self.turns else []

    def clear(self) -> None:
        """Clear all session turn history and entity tracking."""
        self.turns.clear()
        self.entity_history.clear()
        self.primary_topic = None
        self.active_clarification = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "session_id": self.session_id,
            "turn_count": len(self.turns),
            "turns": [t.to_dict() for t in self.turns],
            "active_clarification": self.active_clarification.to_dict() if self.active_clarification else None,
            "entity_history": self.entity_history,
            "primary_topic": self.primary_topic,
            "created_at": self.created_at
        }

@dataclass
class OrchestrationResult:
    """End-to-end execution trace produced by MultiAgentOrchestrator."""
    query: str
    response: AgentResponse
    retrieval_result: Optional[RetrievalResult] = None
    execution_time_ms: float = 0.0
    status: str = "success"
    clarification_request: Optional[ClarificationRequest] = None
    contextualized_query: Optional[str] = None
    session_id: Optional[str] = None
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "response": self.response.to_dict(),
            "retrieval_result": self.retrieval_result.to_dict() if self.retrieval_result else None,
            "execution_time_ms": self.execution_time_ms,
            "status": self.status,
            "clarification_request": self.clarification_request.to_dict() if self.clarification_request else None,
            "contextualized_query": self.contextualized_query,
            "session_id": self.session_id,
            "error": self.error
        }
