"""Data models and schemas for Milestone 3 Multi-Agent Query Resolution System.

Extends Milestone 2 models with comprehensive support for:
- ClarificationType & ClarificationRequest (M3.1)
- ClarificationResponse & ClarificationStatus (M3.1)
- Multi-part query analysis (M3.1)
"""
import time
import uuid
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import List, Dict, Any, Optional

class QueryType(str, Enum):
    FACTUAL = "factual"
    PROCEDURAL = "procedural"
    COMPARATIVE = "comparative"
    AMBIGUOUS = "ambiguous"
    MULTI_PART = "multi_part"

class RoutingTarget(str, Enum):
    RETRIEVAL = "retrieval"
    CLARIFICATION = "clarification"

class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NONE = "NONE"

class ClarificationType(str, Enum):
    AMBIGUOUS_TERM = "ambiguous_term"
    MISSING_CONTEXT = "missing_context"
    INCOMPLETE_REQUEST = "incomplete_request"
    MULTIPLE_INTERPRETATIONS = "multiple_interpretations"
    MULTI_PART_UNRESOLVED = "multi_part_unresolved"
    INSUFFICIENT_INFORMATION = "insufficient_information"

class ClarificationStatus(str, Enum):
    PENDING = "pending"
    RESOLVED = "resolved"
    CANCELLED = "cancelled"

@dataclass
class ClarificationRequest:
    """Detailed clarification proposal produced by the Clarification Agent (M3.1)."""
    original_query: str
    clarification_type: ClarificationType
    reason: str
    follow_up_question: str
    suggested_options: List[str] = field(default_factory=list)
    sub_questions: List[str] = field(default_factory=list)
    is_multi_part: bool = False
    clarification_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    status: ClarificationStatus = ClarificationStatus.PENDING
    created_at: float = field(default_factory=time.time)
    resolved_at: Optional[float] = None
    user_response: Optional[str] = None
    refined_query: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "clarification_id": self.clarification_id,
            "original_query": self.original_query,
            "clarification_type": self.clarification_type.value,
            "reason": self.reason,
            "follow_up_question": self.follow_up_question,
            "suggested_options": self.suggested_options,
            "sub_questions": self.sub_questions,
            "is_multi_part": self.is_multi_part,
            "status": self.status.value,
            "created_at": self.created_at,
            "resolved_at": self.resolved_at,
            "user_response": self.user_response,
            "refined_query": self.refined_query
        }

@dataclass
class QueryAnalysisResult:
    """Output generated by the Query Understanding & Clarification analysis."""
    query: str
    cleaned_query: str
    query_type: QueryType
    classification_confidence: float = 0.0
    route_to: RoutingTarget = RoutingTarget.RETRIEVAL
    reasoning: str = ""
    entities: List[str] = field(default_factory=list)
    requires_clarification: bool = False
    clarification_request: Optional[ClarificationRequest] = None
    reformulated_query: Optional[str] = None
    sub_questions: List[str] = field(default_factory=list)
    confidence: Optional[float] = None

    def __post_init__(self):
        if self.confidence is not None and not self.classification_confidence:
            self.classification_confidence = self.confidence
        elif self.classification_confidence and self.confidence is None:
            self.confidence = self.classification_confidence

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "cleaned_query": self.cleaned_query,
            "query_type": self.query_type.value,
            "classification_confidence": self.classification_confidence,
            "confidence": self.classification_confidence,
            "route_to": self.route_to.value,
            "reasoning": self.reasoning,
            "entities": self.entities,
            "requires_clarification": self.requires_clarification,
            "clarification_request": self.clarification_request.to_dict() if self.clarification_request else None,
            "reformulated_query": self.reformulated_query,
            "sub_questions": self.sub_questions
        }

@dataclass
class RetrievalChunk:
    """A ranked knowledge base chunk with metadata and similarity score."""
    chunk_id: str
    content: str
    metadata: Dict[str, Any]
    similarity_score: float
    rank: int
    document_name: str = ""
    page: Optional[int] = None
    section: Optional[str] = None

    def __post_init__(self):
        if not self.document_name and self.metadata:
            self.document_name = self.metadata.get("document_name") or self.metadata.get("source", "Unknown")
        if self.page is None and self.metadata:
            raw_page = self.metadata.get("page")
            self.page = raw_page if (raw_page is not None and raw_page != 0) else None
        if self.section is None and self.metadata:
            self.section = self.metadata.get("section")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "chunk_id": self.chunk_id,
            "content": self.content,
            "metadata": self.metadata,
            "similarity_score": self.similarity_score,
            "rank": self.rank,
            "document_name": self.document_name,
            "page": self.page,
            "section": self.section
        }

@dataclass
class RetrievalResult:
    """Output generated by the Retrieval Agent."""
    query: str
    query_type: QueryType
    chunks: List[RetrievalChunk]
    top_score: float
    total_retrieved: int
    filtered_count: int
    has_sufficient_evidence: bool
    confidence_threshold: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "query_type": self.query_type.value,
            "chunks": [c.to_dict() for c in self.chunks],
            "top_score": self.top_score,
            "total_retrieved": self.total_retrieved,
            "filtered_count": self.filtered_count,
            "has_sufficient_evidence": self.has_sufficient_evidence,
            "confidence_threshold": self.confidence_threshold
        }

@dataclass
class SourceAttribution:
    """Citation metadata for grounded response attribution."""
    document_name: str
    chunk_id: str
    relevance_score: float
    snippet: str
    page: Optional[int] = None
    section: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "document_name": self.document_name,
            "chunk_id": self.chunk_id,
            "relevance_score": self.relevance_score,
            "snippet": self.snippet,
            "page": self.page,
            "section": self.section
        }

@dataclass
class AgentResponse:
    """Output generated by the Response Generation or Clarification Agent."""
    answer: str
    confidence_score: float
    confidence_level: ConfidenceLevel
    sources: List[SourceAttribution]
    query_analysis: QueryAnalysisResult
    has_sufficient_evidence: bool = True
    requires_clarification: bool = False
    clarification_request: Optional[ClarificationRequest] = None
    is_clarified_resolution: bool = False
    refined_query: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "answer": self.answer,
            "confidence_score": self.confidence_score,
            "confidence_level": self.confidence_level.value,
            "sources": [s.to_dict() for s in self.sources],
            "query_analysis": self.query_analysis.to_dict(),
            "has_sufficient_evidence": self.has_sufficient_evidence,
            "requires_clarification": self.requires_clarification,
            "clarification_request": self.clarification_request.to_dict() if self.clarification_request else None,
            "is_clarified_resolution": self.is_clarified_resolution,
            "refined_query": self.refined_query
        }

@dataclass
class OrchestrationResult:
    """End-to-end execution trace produced by MultiAgentOrchestrator."""
    query: str
    response: AgentResponse
    retrieval_result: Optional[RetrievalResult] = None
    execution_time_ms: float = 0.0
    status: str = "success"
    clarification_request: Optional[ClarificationRequest] = None
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "response": self.response.to_dict(),
            "retrieval_result": self.retrieval_result.to_dict() if self.retrieval_result else None,
            "execution_time_ms": self.execution_time_ms,
            "status": self.status,
            "clarification_request": self.clarification_request.to_dict() if self.clarification_request else None,
            "error": self.error
        }
